"""Generate js/stack.js: the tech-stack tiles data used by the Skills section.

Reads tools/tech.json (categories + technologies) and tools/glyphs.json (logo paths,
bounding boxes and brand colours, from Simple Icons and the AWS Architecture Icons)
and emits a single compact JS file.

Each technology carries its brand colour pre-resolved for both site themes, so the
page never has to do colour maths at runtime and theme switching is instant. A brand
colour that would not read on the tile is lightened (dark theme) or darkened (light
theme) in HLS until it clears the WCAG contrast floor.

Usage:  python tools/build_stack.py
"""
import colorsys
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

# Tile background per theme, taken from css/style.css (--card-bg).
THEMES = {
    "dark":  {"bg": "#1a1a1a", "text": "#ffffff", "minContrast": 4.5, "step": 0.02},
    "light": {"bg": "#ffffff", "text": "#0a0f14", "minContrast": 3.0, "step": -0.02},
}

# Brand colours where a mechanical lighten/darken would lose the identity.
OVERRIDES = {
    ("aws", "dark"): "#FF9900",
    ("javascript", "light"): "#C9A800",
}


def rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))


def hexs(c):
    return "#" + "".join(f"{round(max(0, min(1, v)) * 255):02X}" for v in c)


def luminance(h):
    def f(c):
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = rgb(h)
    return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b)


def contrast(a, b):
    la, lb = sorted((luminance(a), luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def legible(hex_, theme, key):
    """Brand colour nudged in HLS until it reads on this theme's tile."""
    t = THEMES[theme]
    if (key, theme) in OVERRIDES:
        return OVERRIDES[(key, theme)]
    base = "#" + hex_.lstrip("#")
    if contrast(base, t["bg"]) >= t["minContrast"]:
        return base
    h, l, s = colorsys.rgb_to_hls(*rgb(base))
    if s < 0.15:
        # Black / grey brands (Kafka, OpenJDK, Ollama...): use the theme's text colour.
        return t["text"]
    for _ in range(60):
        l = max(0.0, min(1.0, l + t["step"]))
        cand = hexs(colorsys.hls_to_rgb(h, l, s if s > 0.05 else 0))
        if contrast(cand, t["bg"]) >= t["minContrast"]:
            return cand
    return t["text"]


def main():
    tech = json.loads((HERE / "tech.json").read_text(encoding="utf-8"))
    glyphs = json.loads((HERE / "glyphs.json").read_text(encoding="utf-8"))

    missing = [t["key"] for t in tech["tech"] if t["key"] not in glyphs]
    if missing:
        raise SystemExit(f"missing glyphs for: {', '.join(missing)}")

    items = []
    for t in tech["tech"]:
        g = glyphs[t["key"]]
        x0, y0, x1, y1 = g["bbox"]
        items.append({
            "k": t["key"],
            "n": t["name"],
            "c": t["cat"],
            # viewBox tightened to the glyph's real bounding box so every logo
            # optically fills the same area regardless of its source padding.
            "b": [round(x0, 2), round(y0, 2), round(x1 - x0, 2), round(y1 - y0, 2)],
            "p": g["paths"],
            "f": 1 if g.get("fillRule") == "evenodd" else 0,
            "d": legible(g["hex"], "dark", t["key"]),
            "l": legible(g["hex"], "light", t["key"]),
        })

    payload = {
        "categories": [{"id": c["id"], "title": c["title"]} for c in tech["categories"]],
        "tech": items,
    }
    js = ("/* Generated by tools/build_stack.py from tools/tech.json and tools/glyphs.json.\n"
          "   Edit those and rebuild; do not hand-edit this file.\n"
          "   Logos: Simple Icons (CC0) and the AWS Architecture Icons. */\n"
          "window.TECH_STACK=" + json.dumps(payload, separators=(",", ":"), ensure_ascii=False) + ";\n")
    out = ROOT / "js" / "stack.js"
    out.write_text(js, encoding="utf-8")
    print(f"js/stack.js  {len(js.encode('utf-8')):,} bytes  "
          f"({len(items)} technologies, {len(payload['categories'])} categories)")


if __name__ == "__main__":
    main()
